# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'WilsonFileManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WilsonFileManager
  pod 'Masonry', '~> 1.1.0'
  pod 'GCDWebServer/WebUploader', '~> 3.4.2'
  pod 'GCDWebServer/Core', '~> 3.4.2'
  pod 'GCDWebServer/WebDAV', '~> 3.4.2'
  pod 'MJExtension', '~> 3.0.13'
  pod 'WilsonDiary', '~> 0.0.5'

  target 'WilsonFileManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WilsonFileManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
